
servicePort = 9092
serviceHost = "0.0.0.0"


mongoHost = "mongodb"
mongoPort = 27017
mongoDatabase = "transport_ticketing_system"


kafkaBootstrapServers = "kafka:9092"
scheduleUpdatesTopic = "schedule-updates"
routeEventsTopic = "route-events"