version: '3.8'

services:
  admin-service:
    build: .
    container_name: admin-service
    ports:
      - "9096:9096"
    environment:
      - ADMIN_SERVICE_PORT=9096
      - PASSENGER_SERVICE_HOST=passenger-service
      - PASSENGER_SERVICE_PORT=9091
      - TRANSPORT_SERVICE_HOST=transport-service
      - TRANSPORT_SERVICE_PORT=9092
      - PAYMENT_SERVICE_HOST=payment-service
      - PAYMENT_SERVICE_PORT=9094
      - TICKETING_SERVICE_HOST=ticketing-service
      - TICKETING_SERVICE_PORT=9095
      - NOTIFICATION_SERVICE_HOST=notification-service
      - NOTIFICATION_SERVICE_PORT=9097
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - mongodb
      - kafka
    networks:
      - transport-network

  mongodb:
    image: mongo:8.2.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - transport-network

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka-data:/tmp/kraft-combined-logs
    networks:
      - transport-network

volumes:
  mongodb-data:
  kafka-data:

networks:
  transport-network:
    driver: bridge