version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:8.2.0
    container_name: transport-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - transport-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # Kafka
  kafka:
    image: apache/kafka:latest
    container_name: transport-kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      CLUSTER_ID: 'transport-cluster-001'
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - transport-network
    healthcheck:
      test: kafka-broker-api-versions --bootstrap-server localhost:9092
      interval: 10s
      timeout: 5s
      retries: 5

  # Notification Service
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-service
    environment:
      - mongoHost=mongodb
      - mongoPort=27017
      - mongoDatabase=transport_ticketing_system
      - kafkaBootstrapServers=kafka:9092
      - kafkaGroupId=notification-service-group
      - scheduleUpdatesTopic=schedule-updates
      - ticketValidatedTopic=ticket-validated
      - paymentsProcessedTopic=payments-processed
      - ticketCreatedTopic=ticket-created
      - enableConsoleOutput=true
      - enableEmailSimulation=true
      - enableSmsSimulation=true
    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - transport-network
    restart: unless-stopped

networks:
  transport-network:
    driver: bridge

volumes:
  mongodb_data:
  kafka_data: